// export { dictA } from './dictA.js'
// export { dictB } from './dictB.js'
// export { dictC } from './dictC.js'
// export { dictD } from './dictD.js'
// export { dictE } from './dictE.js'
// export { dictF } from './dictF.js'
// export { dictG } from './dictG.js'
// export { dictH } from './dictH.js'
// export { dictI } from './dictI.js'
// export { dictJ } from './dictJ.js'
// export { dictK } from './dictK.js'
// export { dictL } from './dictL.js'
// export { dictM } from './dictM.js'
// export { dictN } from './dictN.js'
// export { dictO } from './dictO.js'
// export { dictP } from './dictP.js'
// export { dictQ } from './dictQ.js'
// export { dictR } from './dictR.js'
// export { dictS } from './dictS.js'
// export { dictT } from './dictT.js'
// export { dictU } from './dictU.js'
// export { dictV } from './dictV.js'
// export { dictW } from './dictW.js'
// export { dictX } from './dictX.js'
// export { dictY } from './dictY.js'
// export { dictZ } from './dictZ.js'
// const { dictA } = require('./dictA.js')
// const { dictB } = require('./dictB.js')
// const { dictC } = require('./dictC.js')
// const { dictD } = require('./dictD.js')
// const { dictE } = require('./dictE.js')
// const { dictF } = require('./dictF.js')
// const { dictG } = require('./dictG.js')
// const { dictH } = require('./dictH.js')
// const { dictI } = require('./dictI.js')
// const { dictJ } = require('./dictJ.js')
// const { dictK } = require('./dictK.js')
// const { dictL } = require('./dictL.js')
// const { dictM } = require('./dictM.js')
// const { dictN } = require('./dictN.js')
// const { dictO } = require('./dictO.js')
// const { dictP } = require('./dictP.js')
// const { dictQ } = require('./dictQ.js')
// const { dictR } = require('./dictR.js')
// const { dictS } = require('./dictS.js')
// const { dictT } = require('./dictT.js')
// const { dictU } = require('./dictU.js')
// const { dictV } = require('./dictV.js')
// const { dictW } = require('./dictW.js')
// const { dictX } = require('./dictX.js')
// const { dictY } = require('./dictY.js')
// const { dictZ } = require('./dictZ.js')